import 'package:flutter/material.dart';
import 'product.dart';

/// Dữ liệu sản phẩm thực tế cho ứng dụng TechStore
final List<Product> sampleProducts = [
  Product(
    id: 'prod_01',
    name: 'iPhone 16 Pro Max 256GB',
    category: 'Điện thoại',
    brand: 'Apple',
    price: 34990000,
    originalPrice: 37990000,
    rating: 4.9,
    reviewCount: 245,
    description:
        'iPhone 16 Pro Max sở hữu thiết kế titan cấp 5 bền nhẹ, màn hình Super Retina XDR 6.9 inch với viền mỏng nhất từ trước đến nay. Trang bị chip A18 Pro mạnh mẽ vượt trội cùng nút điều khiển camera (Camera Control) hoàn toàn mới.',
    specifications: {
      'Màn hình': '6.9" OLED Super Retina XDR 120Hz',
      'Chip xử lý': 'Apple A18 Pro 6 nhân',
      'RAM': '8 GB',
      'Bộ nhớ trong': '256 GB',
      'Camera sau': 'Chính 48MP + Góc siêu rộng 48MP + Tele 5x 12MP',
      'Pin': '4.685 mAh, Sạc nhanh 25W',
    },
    icon: Icons.phone_iphone,
    themeColor: const Color(0xFF4A4E69),
    stock: 15,
  ),
  Product(
    id: 'prod_02',
    name: 'MacBook Pro 14" M3 Pro',
    category: 'Laptop',
    brand: 'Apple',
    price: 49990000,
    originalPrice: 52990000,
    rating: 4.8,
    reviewCount: 118,
    description:
        'MacBook Pro 14 inch trang bị chip Apple M3 Pro mang lại hiệu năng đỉnh cao cho công việc lập trình và thiết kế chuyên nghiệp. Màn hình Liquid Retina XDR độ sáng tối đa 1600 nits, thời lượng pin lên đến 22 giờ liên tục.',
    specifications: {
      'Màn hình': '14.2" Liquid Retina XDR (3024 x 1964) 120Hz',
      'CPU': 'Apple M3 Pro 11 nhân',
      'GPU': '14 nhân đồ họa',
      'RAM': '18 GB Unified Memory',
      'Ổ cứng': '512 GB SSD siêu tốc',
      'Trọng lượng': '1.61 kg',
    },
    icon: Icons.laptop_mac,
    themeColor: const Color(0xFF22223B),
    stock: 8,
  ),
  Product(
    id: 'prod_03',
    name: 'Sony WH-1000XM5 Noise Canceling',
    category: 'Âm thanh',
    brand: 'Sony',
    price: 6990000,
    originalPrice: 8490000,
    rating: 4.7,
    reviewCount: 312,
    description:
        'Tai nghe chụp tai chống ồn chủ động hàng đầu thế giới với bộ xử lý Integrated Processor V1 và HD QN1. Hỗ trợ âm thanh Hi-Res Audio Wireless LDAC, đàm thoại chuẩn AI với 4 micro beamforming và pin 30 giờ.',
    specifications: {
      'Loại tai nghe': 'Over-ear Chống ồn chủ động (ANC)',
      'Thời lượng pin': '30 giờ (bật ANC), 40 giờ (tắt ANC)',
      'Cổng sạc': 'USB-C (sạc nhanh 3 phút được 3 giờ)',
      'Kết nối': 'Bluetooth 5.2, Multipoint 2 thiết bị',
      'Trọng lượng': '250 g',
    },
    icon: Icons.headphones,
    themeColor: const Color(0xFF1D3557),
    stock: 22,
  ),
  Product(
    id: 'prod_04',
    name: 'Apple Watch Ultra 2 GPS + Cellular',
    category: 'Đồng hồ',
    brand: 'Apple',
    price: 21490000,
    originalPrice: 22990000,
    rating: 4.9,
    reviewCount: 89,
    description:
        'Đồng hồ thể thao chuyên nghiệp với khung vỏ titan 49mm, mặt kính sapphire chống trầy xước và độ sáng màn hình lên tới 3000 nits. GPS băng tần kép chuẩn L1 & L5 cực kỳ chính xác cho các hoạt động thám hiểm ngoài trời.',
    specifications: {
      'Kích thước vỏ': '49 mm Hợp kim Titan',
      'Độ sáng': 'Tối đa 3000 nits',
      'Chống nước': '100m, chứng nhận lặn EN13319',
      'Thời lượng pin': '36 giờ (chế độ thường), 72 giờ (tiết kiệm)',
      'Cảm biến': 'Nhịp tim, ECG, SpO2, Đo nhiệt độ',
    },
    icon: Icons.watch,
    themeColor: const Color(0xFFE76F51),
    stock: 10,
  ),
  Product(
    id: 'prod_05',
    name: 'iPad Pro 11" M4 Wi-Fi 256GB',
    category: 'Máy tính bảng',
    brand: 'Apple',
    price: 27990000,
    originalPrice: 29990000,
    rating: 4.8,
    reviewCount: 96,
    description:
        'Chiếc iPad mỏng nhất từ trước tới nay chỉ 5.3mm. Trang bị màn hình Ultra Retina XDR công nghệ OLED hai lớp (Tandem OLED) siêu sáng và chip Apple M4 thế hệ mới với công cụ thần kinh Neural Engine vượt trội.',
    specifications: {
      'Màn hình': '11" Ultra Retina XDR Tandem OLED 120Hz',
      'Chip xử lý': 'Apple M4 9 nhân CPU, 10 nhân GPU',
      'RAM': '8 GB',
      'Bộ nhớ': '256 GB',
      'Độ mỏng': '5.3 mm siêu nhẹ',
      'Tương thích': 'Apple Pencil Pro, Magic Keyboard mới',
    },
    icon: Icons.tablet_mac,
    themeColor: const Color(0xFF2A9D8F),
    stock: 12,
  ),
  Product(
    id: 'prod_06',
    name: 'Bàn phím cơ Keychron Q1 Pro Wireless',
    category: 'Phụ kiện',
    brand: 'Keychron',
    price: 4390000,
    originalPrice: 4890000,
    rating: 4.6,
    reviewCount: 64,
    description:
        'Bàn phím cơ công thái học cao cấp layout 75% Full nhôm CNC nguyên khối. Thiết kế Double Gasket Mount êm ái, switch Keychron K Pro trơn tru, hỗ trợ kết nối Bluetooth 5.1 và tương thích hoàn hảo cả macOS lẫn Windows.',
    specifications: {
      'Layout': '75% (81 phím + Núm xoay Knob kim loại)',
      'Chất liệu vỏ': 'Nhôm 6063 gia công CNC',
      'Kết nối': 'Bluetooth 5.1 & Type-C có dây',
      'Hot-swap': 'Có (hỗ trợ switch 3-pin & 5-pin)',
      'Hệ điều hành': 'macOS / Windows / Linux / Android',
    },
    icon: Icons.keyboard,
    themeColor: const Color(0xFF6D597A),
    stock: 18,
  ),
];
